# Taken from https://github.com/CenterForOpenScience/osf.io/pull/6364/files#diff-4e5e90c6228fd48698d074241c2ba760R1
# Install the Docker Client
# - https://www.docker.com/products/docker-desktop

version: '3.4'

volumes:
  postgres_data_vol:
    external: false
  elasticsearch_data_vol:
    external: false
  rabbitmq_vol:
    external: false
  share_vol:
    external: false
  share_dist_vol:
    external: false
  share_requirements_vol:
    external: false

services:


  ####################
  # Backend Services #
  ####################

  elasticsearch:
    image: elasticsearch:5.4
    ports:
      - 9203:9200
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data_vol:/usr/share/elasticsearch/data
    stdin_open: true

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    stdin_open: true

  postgres:
    image: postgres:10
    command:
      - /bin/bash
      - -c
      - echo "$$POSTGRES_INITDB" > /docker-entrypoint-initdb.d/commands.sh &&
        chmod +x /docker-entrypoint-initdb.d/commands.sh &&
        /docker-entrypoint.sh postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: share
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB: |
        sed -i -e 's/max_connections.*/max_connections = 5000/' /var/lib/postgresql/data/postgresql.conf
        sed -i -e 's/#log_min_duration_statement = .*/log_min_duration_statement = 0/' /var/lib/postgresql/data/postgresql.conf
    volumes:
      - "${POSTGRES_DATA_VOL:-postgres_data_vol}:/var/lib/postgresql/data/"
    stdin_open: true
    env_file:
      - .docker-compose.env

  ##################
  # SHARE software #
  ##################

  requirements:
    image: quay.io/centerforopenscience/share:develop
        # /usr/local/bin/python -m pip install --upgrade pip  &&
        # pip install -e . &&
        # pip install watchdog[watchmedo]
        # apt autoremove -y &&
    command:
      - /bin/bash
      - -c
      - apt-get update &&
        apt-get install -y gcc libyaml-dev telnet &&
        pip install -U pip &&
        pip install -r requirements.txt -r dev-requirements.txt &&
        (python3 -m compileall /usr/local/lib/python3.6 || true) &&
        rm -Rf /python3.6/* &&
        apt-get remove -y gcc &&
        cp -Rf -p /usr/local/lib/python3.6 / &&
        python3 setup.py develop
    restart: 'no'
    volumes:
      - ./:/code:cached
      - share_requirements_vol:/python3.6

  frontend:
    image: quay.io/centerforopenscience/share-web:develop-local
    command: yarn start
    ports:
      - 4204:4200
    volumes:
      - share_dist_vol:/code/dist
    stdin_open: true

  worker:
    image: quay.io/centerforopenscience/share:develop
    # command: pip install watchdog[watchmedo] && watchmedo auto-restart --directory="/code:cached" --pattern="*.py" --recursive -- /usr/local/bin/celery worker --app=project --uid=daemon --loglevel=INFO
    command: /usr/local/bin/celery --app project worker --uid daemon -l INFO
    # command: 
    #   - watchmedo auto-restart --directory=/code:cached --pattern=*.py --recursive -- \
    #     /usr/local/bin/celery --app project worker --uid daemon -l INFO
    depends_on:
      - postgres
      - rabbitmq
      - web
      - elasticsearch
      - indexer
    volumes:
      # - ./.pdbrc.py:/root/.pdbrc.py
      - ./:/code:cached
      - share_requirements_vol:/usr/local/lib/python3.6
    env_file:
      - .docker-compose.env
    stdin_open: true
    tty: true
    ports:
      # - 6900-7000:6900-7000
      - 6944:6942
      # - 6904:6900
    environment:
      - CELERY_RDB_HOST=0.0.0.0. # to be able to telnet from outside the container
      # - CELERY_RDB_PORT=6900
      - CELERY_RDB_PORT=6942
      - PYTHONUNBUFFERED=1       # any non-empty string will do    

  web:
    image: quay.io/centerforopenscience/share:develop
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8003:8000
    depends_on:
      - postgres
      - rabbitmq
      - elasticsearch
      - frontend
    volumes:
      - ./:/code:cached
      - share_requirements_vol:/usr/local/lib/python3.6
    env_file:
      - .docker-compose.env
    stdin_open: true
    tty: true

  indexer:
    image: quay.io/centerforopenscience/share:develop
    command: sharectl search daemon
    depends_on:
      - postgres
      - rabbitmq
      - elasticsearch
    volumes:
      - ./:/code:cached
      - share_requirements_vol:/usr/local/lib/python3.6
    env_file:
      - .docker-compose.env
    stdin_open: true

